language: node_js
sudo: required
dist: trusty
os: linux
git:
  depth: 1
cache:
  directories:
    - "node_modules"
services:
  - cassandra
node_js:
  - '0.10'
  - '4'
  - '6'
  - '8'
  - '10'
matrix:
  allow_failures:
    - node_js: '0.10'
